// Pure data — safe to import from client components (no server-only deps).
//
// National Occupational Classification (NOC) 2021 unit groups — the 5-digit
// codes Canadian employers, ESDC, and IRCC use to identify an occupation. All
// 516 unit groups are listed.
//
// Scraped from https://pioverseas.com/canada-noc/ on 2026-09-02.
// That is a third-party immigration site, NOT Statistics Canada — the official
// source (noc.esdc.gc.ca) could not be fetched to cross-check the titles. The
// structure was validated: 516 unique codes, every TEER digit in range, all ten
// broad categories present. Treat individual titles as unverified; re-generate
// from the official source when one is reachable.
//
// Regenerate: node scripts/gen-noc.mjs

export interface NocUnitGroup {
  /** 5-digit NOC 2021 unit group code. */
  code: string
  /** Official occupation title for the unit group. */
  title: string
}

/**
 * TEER (Training, Education, Experience and Responsibilities) category.
 * In NOC 2021 the SECOND digit of the code IS the TEER category, so this is
 * derived rather than stored. Express Entry programs generally require TEER 0-3.
 */
export type TeerCategory = 0 | 1 | 2 | 3 | 4 | 5

export const TEER_LABELS: Record<TeerCategory, string> = {
  0: 'Management occupations',
  1: 'University degree',
  2: 'College diploma, apprenticeship (2+ years), or supervisory role',
  3: 'College diploma (under 2 years) or apprenticeship (under 2 years)',
  4: 'High school diploma or several weeks of on-the-job training',
  5: 'Short work demonstration, no formal education required',
}

/** First digit of the code — the NOC broad occupational category. */
export const BROAD_CATEGORIES: Record<string, string> = {
  '0': 'Legislative and senior management occupations',
  '1': 'Business, finance and administration occupations',
  '2': 'Natural and applied sciences and related occupations',
  '3': 'Health occupations',
  '4': 'Education, law and social, community and government services',
  '5': 'Art, culture, recreation and sport occupations',
  '6': 'Sales and service occupations',
  '7': 'Trades, transport and equipment operators and related occupations',
  '8': 'Natural resources, agriculture and related production occupations',
  '9': 'Manufacturing and utilities occupations',
}

export const NOC_UNIT_GROUPS: readonly NocUnitGroup[] = [
  { code: '00010', title: 'Legislators' },
  { code: '00011', title: 'Senior government managers and officials' },
  { code: '00012', title: 'Senior managers – financial, communications and other business services' },
  { code: '00013', title: 'Senior managers – health, education, social and community services and membership organizations' },
  { code: '00014', title: 'Senior managers – trade, broadcasting and other services' },
  { code: '00015', title: 'Senior managers – construction, transportation, production and utilities' },
  { code: '10010', title: 'Financial managers' },
  { code: '10011', title: 'Human resources managers' },
  { code: '10012', title: 'Purchasing managers' },
  { code: '10019', title: 'Other administrative services managers' },
  { code: '10020', title: 'Insurance, real estate and financial brokerage managers' },
  { code: '10021', title: 'Banking, credit and other investment managers' },
  { code: '10022', title: 'Advertising, marketing and public relations managers' },
  { code: '10029', title: 'Other business services managers' },
  { code: '10030', title: 'Telecommunication carriers managers' },
  { code: '11100', title: 'Financial auditors and accountants' },
  { code: '11101', title: 'Financial and investment analysts' },
  { code: '11102', title: 'Financial advisors' },
  { code: '11103', title: 'Securities agents, investment dealers, and brokers' },
  { code: '11109', title: 'Other financial officers' },
  { code: '11200', title: 'Human resources professionals' },
  { code: '11201', title: 'Professional occupations in business management consulting' },
  { code: '11202', title: 'Professional occupations in advertising, marketing and public relations' },
  { code: '12010', title: 'Supervisors, general office, and administrative support workers' },
  { code: '12011', title: 'Supervisors, finance and insurance office workers' },
  { code: '12012', title: 'Supervisors, library, correspondence, and related information workers' },
  { code: '12013', title: 'Supervisors, supply chain, tracking and scheduling coordination occupations' },
  { code: '12100', title: 'Executive assistants' },
  { code: '12101', title: 'Human resources and recruitment officers' },
  { code: '12102', title: 'Procurement and purchasing agents and officers' },
  { code: '12103', title: 'Conference and event planners' },
  { code: '12104', title: 'Employment insurance and revenue officers' },
  { code: '12110', title: 'Court reporters, medical transcriptionists, and related occupations' },
  { code: '12111', title: 'Health information management occupations' },
  { code: '12112', title: 'Records management technicians' },
  { code: '12113', title: 'Statistical officers and related research support occupations' },
  { code: '12200', title: 'Accounting technicians and bookkeepers' },
  { code: '12201', title: 'Insurance adjusters and claims examiners' },
  { code: '12202', title: 'Insurance underwriters' },
  { code: '12203', title: 'Assessors, business valuators, and appraisers' },
  { code: '13100', title: 'Administrative officers' },
  { code: '13101', title: 'Property administrators' },
  { code: '13102', title: 'Payroll administrators' },
  { code: '13110', title: 'Administrative assistants' },
  { code: '13111', title: 'Legal administrative assistants' },
  { code: '13112', title: 'Medical administrative assistants' },
  { code: '13200', title: 'Customs, ship, and other brokers' },
  { code: '13201', title: 'Production and transportation logistics coordinators' },
  { code: '14100', title: 'General office support workers' },
  { code: '14101', title: 'Receptionists' },
  { code: '14102', title: 'Personnel clerks' },
  { code: '14103', title: 'Court clerks and related court services occupations' },
  { code: '14110', title: 'Survey interviewers and statistical clerks' },
  { code: '14111', title: 'Data entry clerks' },
  { code: '14112', title: 'Desktop publishing operators and related occupations' },
  { code: '14200', title: 'Accounting and related clerks' },
  { code: '14201', title: 'Banking, insurance and other financial clerks' },
  { code: '14202', title: 'Collection clerks' },
  { code: '14300', title: 'Library assistants and clerks' },
  { code: '14301', title: 'Correspondence, publication and regulatory clerks' },
  { code: '14400', title: 'Shippers and receivers' },
  { code: '14401', title: 'Storekeepers and partspersons' },
  { code: '14402', title: 'Production logistics workers' },
  { code: '14403', title: 'Purchasing and inventory control workers' },
  { code: '14404', title: 'Dispatchers' },
  { code: '14405', title: 'Transportation route and crew schedulers' },
  { code: '20010', title: 'Engineering managers' },
  { code: '20011', title: 'Architecture and science managers' },
  { code: '20012', title: 'Computer and information systems managers' },
  { code: '21100', title: 'Physicists and astronomers' },
  { code: '21101', title: 'Chemists' },
  { code: '21102', title: 'Geoscientists and oceanographers' },
  { code: '21103', title: 'Meteorologists and climatologists' },
  { code: '21109', title: 'Other professional occupations in the physical sciences' },
  { code: '21110', title: 'Biologists and related scientists' },
  { code: '21111', title: 'Forestry professionals' },
  { code: '21112', title: 'Agricultural representatives, consultants and specialists' },
  { code: '21120', title: 'Public and environmental health and safety professionals' },
  { code: '21200', title: 'Architects' },
  { code: '21201', title: 'Landscape architects' },
  { code: '21202', title: 'Urban and land use planners' },
  { code: '21203', title: 'Land surveyors' },
  { code: '21210', title: 'Mathematicians, statisticians, and actuaries' },
  { code: '21211', title: 'Data scientists' },
  { code: '21220', title: 'Cybersecurity specialists' },
  { code: '21221', title: 'Business systems specialists' },
  { code: '21222', title: 'Information systems specialists' },
  { code: '21223', title: 'Database analysts and data administrators' },
  { code: '21230', title: 'Computer systems developers and programmers' },
  { code: '21231', title: 'Software engineers and designers' },
  { code: '21232', title: 'Software developers and programmers' },
  { code: '21233', title: 'Web designers' },
  { code: '21234', title: 'Web developers and programmers' },
  { code: '21300', title: 'Civil engineers' },
  { code: '21301', title: 'Mechanical engineers' },
  { code: '21310', title: 'Electrical and electronics engineers' },
  { code: '21311', title: 'Computer engineers (except software engineers and designers)' },
  { code: '21320', title: 'Chemical engineers' },
  { code: '21321', title: 'Industrial and manufacturing engineers' },
  { code: '21322', title: 'Metallurgical and materials engineers' },
  { code: '21330', title: 'Mining engineers' },
  { code: '21331', title: 'Geological engineers' },
  { code: '21332', title: 'Petroleum engineers' },
  { code: '21390', title: 'Aerospace engineers' },
  { code: '21399', title: 'Other professional engineers' },
  { code: '22100', title: 'Chemical technologists and technicians' },
  { code: '22101', title: 'Geological and mineral technologists and technicians' },
  { code: '22110', title: 'Biological technologists and technicians' },
  { code: '22111', title: 'Agricultural and fish products inspectors' },
  { code: '22112', title: 'Forestry technologists and technicians' },
  { code: '22113', title: 'Conservation and fishery officers' },
  { code: '22114', title: 'Landscape and horticulture technicians and specialists' },
  { code: '22210', title: 'Architectural technologists and technicians' },
  { code: '22211', title: 'Industrial designers' },
  { code: '22212', title: 'Drafting technologists and technicians' },
  { code: '22213', title: 'Land survey technologists and technicians' },
  { code: '22214', title: 'Technical occupations in geomatics and meteorology' },
  { code: '22220', title: 'Computer network and web technicians' },
  { code: '22221', title: 'User support technicians' },
  { code: '22222', title: 'Information systems testing technicians' },
  { code: '22230', title: 'Non-destructive testers and inspectors' },
  { code: '22231', title: 'Engineering inspectors and regulatory officers' },
  { code: '22232', title: 'Occupational health and safety specialists' },
  { code: '22233', title: 'Construction inspectors' },
  { code: '22300', title: 'Civil engineering technologists and technicians' },
  { code: '22301', title: 'Mechanical engineering technologists and technicians' },
  { code: '22302', title: 'Industrial engineering and manufacturing technologists and technicians' },
  { code: '22303', title: 'Construction estimators' },
  { code: '22310', title: 'Electrical and electronics engineering technologists and technicians' },
  { code: '22311', title: 'Electronic service technicians (household and business equipment)' },
  { code: '22312', title: 'Industrial instrument technicians and mechanics' },
  { code: '22313', title: 'Aircraft instrument, electrical and avionics mechanics, technicians, and inspectors' },
  { code: '30010', title: 'Managers in health care' },
  { code: '31100', title: 'Specialists in clinical and laboratory medicine' },
  { code: '31101', title: 'Specialists in surgery' },
  { code: '31102', title: 'General practitioners and family physicians' },
  { code: '31103', title: 'Veterinarians' },
  { code: '31110', title: 'Dentists' },
  { code: '31111', title: 'Optometrists' },
  { code: '31112', title: 'Audiologists and speech-language pathologists' },
  { code: '31120', title: 'Pharmacists' },
  { code: '31121', title: 'Dietitians and nutritionists' },
  { code: '31200', title: 'Psychologists' },
  { code: '31201', title: 'Chiropractors' },
  { code: '31202', title: 'Physiotherapists' },
  { code: '31203', title: 'Occupational therapists' },
  { code: '31204', title: 'Kinesiologists and other professional occupations in therapy and assessment' },
  { code: '31209', title: 'Other professional occupations in health diagnosing and treating' },
  { code: '31300', title: 'Nursing coordinators and supervisors' },
  { code: '31301', title: 'Registered nurses and registered psychiatric nurses' },
  { code: '31302', title: 'Nurse practitioners' },
  { code: '31303', title: 'Physician assistants, midwives, and allied health professionals' },
  { code: '32100', title: 'Opticians' },
  { code: '32101', title: 'Licensed practical nurses' },
  { code: '32102', title: 'Paramedical occupations' },
  { code: '32103', title: 'Respiratory therapists, clinical perfusionists and cardiopulmonary technologists' },
  { code: '32104', title: 'Animal health technologists and veterinary technicians' },
  { code: '32109', title: 'Other technical occupations in therapy and assessment' },
  { code: '32110', title: 'Denturists' },
  { code: '32111', title: 'Dental hygienists and dental therapists' },
  { code: '32112', title: 'Dental technologists and technicians' },
  { code: '32120', title: 'Medical laboratory technologists' },
  { code: '32121', title: 'Medical radiation technologists' },
  { code: '32122', title: 'Medical sonographers' },
  { code: '32123', title: 'Cardiology technologists and electrophysiological diagnostic technologists' },
  { code: '32124', title: 'Pharmacy technicians' },
  { code: '32129', title: 'Other medical technologists and technicians' },
  { code: '32200', title: 'Traditional Chinese medicine practitioners and acupuncturists' },
  { code: '32201', title: 'Massage therapists' },
  { code: '32209', title: 'Other practitioners of natural healing' },
  { code: '33100', title: 'Dental assistants and dental laboratory assistants' },
  { code: '33101', title: 'Medical laboratory assistants and related technical occupations' },
  { code: '33102', title: 'Nurse aides, orderlies, and patient service associates' },
  { code: '33103', title: 'Pharmacy technical assistants and pharmacy assistants' },
  { code: '33109', title: 'Other assisting occupations in support of health services' },
  { code: '40010', title: 'Government managers – health and social policy development and program administration' },
  { code: '40011', title: 'Government managers – economic analysis, policy development and program administration' },
  { code: '40012', title: 'Government managers – education policy development and program administration' },
  { code: '40019', title: 'Other managers in public administration' },
  { code: '40020', title: 'Administrators – post-secondary education and vocational training' },
  { code: '40021', title: 'School principals and administrators of elementary and secondary education' },
  { code: '40030', title: 'Managers in social, community and correctional services' },
  { code: '40040', title: 'Commissioned police officers and related occupations in public protection services' },
  { code: '40041', title: 'Fire chiefs and senior firefighting officers' },
  { code: '40042', title: 'Commissioned officers of the Canadian Armed Forces' },
  { code: '41100', title: 'Judges' },
  { code: '41101', title: 'Lawyers and Quebec notaries' },
  { code: '41200', title: 'University professors and lecturers' },
  { code: '41201', title: 'Post-secondary teaching and research assistants' },
  { code: '41210', title: 'College and other vocational instructors' },
  { code: '41220', title: 'Secondary school teachers' },
  { code: '41221', title: 'Elementary school and kindergarten teachers' },
  { code: '41300', title: 'Social workers' },
  { code: '41301', title: 'Therapists in counseling and related specialized therapies' },
  { code: '41302', title: 'Religious leaders' },
  { code: '41310', title: 'Police investigators and other investigative occupations' },
  { code: '41311', title: 'Probation and parole officers' },
  { code: '41320', title: 'Educational counselors' },
  { code: '41321', title: 'Career development practitioners and career counselors (except education)' },
  { code: '41400', title: 'Natural and applied science policy researchers, consultants and program officers' },
  { code: '41401', title: 'Economists and economic policy researchers and analysts' },
  { code: '41402', title: 'Business development officers and market researchers and analysts' },
  { code: '41403', title: 'Social policy researchers, consultants, and program officers' },
  { code: '41404', title: 'Health policy researchers, consultants, and program officers' },
  { code: '41405', title: 'Education policy researchers, consultants, and program officers' },
  { code: '41406', title: 'Recreation, sports, and fitness policy researchers, consultants, and program officers' },
  { code: '41407', title: 'Program officers unique to the government' },
  { code: '41409', title: 'Other professional occupations in social science' },
  { code: '42100', title: 'Police officers (except commissioned)' },
  { code: '42101', title: 'Firefighters' },
  { code: '42102', title: 'Specialized members of the Canadian Armed Forces' },
  { code: '42200', title: 'Paralegals and related occupations' },
  { code: '42201', title: 'Social and community service workers' },
  { code: '42202', title: 'Early childhood educators and assistants' },
  { code: '42203', title: 'Instructors of persons with disabilities' },
  { code: '42204', title: 'Religion workers' },
  { code: '43100', title: 'Elementary and secondary school teacher assistants' },
  { code: '43109', title: 'Other instructors' },
  { code: '43200', title: 'Sheriffs and bailiffs' },
  { code: '43201', title: 'Correctional service officers' },
  { code: '43202', title: 'By-law enforcement and other regulatory officers' },
  { code: '43203', title: 'Border services, customs, and immigration officers' },
  { code: '43204', title: 'perations members of the Canadian Armed Forces' },
  { code: '44100', title: 'Home child care providers' },
  { code: '44101', title: 'Home support workers, caregivers and related occupations' },
  { code: '44200', title: 'Primary combat members of the Canadian Armed Forces' },
  { code: '45100', title: 'Student monitors, crossing guards, and related occupations' },
  { code: '50010', title: 'Library, archive, museum and art gallery managers' },
  { code: '50011', title: 'Managers – publishing, motion pictures, broadcasting and performing arts' },
  { code: '50012', title: 'Recreation, sports and fitness program and service directors' },
  { code: '51100', title: 'Librarians' },
  { code: '51101', title: 'Conservators and curators' },
  { code: '51102', title: 'Archivists' },
  { code: '51110', title: 'Editors' },
  { code: '51111', title: 'Authors and writers (except technical)' },
  { code: '51112', title: 'Technical writers' },
  { code: '51113', title: 'Journalists' },
  { code: '51114', title: 'Translators, terminologists, and interpreters' },
  { code: '51120', title: 'Producers, directors, choreographers, and related occupations' },
  { code: '51121', title: 'Conductors, composers, and arrangers' },
  { code: '51122', title: 'Musicians and singers' },
  { code: '52100', title: 'Library and public archive technicians' },
  { code: '52110', title: 'Film and video camera operators' },
  { code: '52111', title: 'Graphic arts technicians' },
  { code: '52112', title: 'Broadcast technicians' },
  { code: '52113', title: 'Audio and video recording technicians' },
  { code: '52114', title: 'Announcers and other broadcasters' },
  { code: '52119', title: 'Other technical and coordinating occupations in motion pictures, broadcasting and the performing arts' },
  { code: '52120', title: 'Graphic designers and illustrators' },
  { code: '52121', title: 'Interior designers and interior decorators' },
  { code: '53100', title: 'Registrars, restorers, interpreters and other occupations related to museum and art galleries' },
  { code: '53110', title: 'Photographers' },
  { code: '53111', title: 'Motion pictures, broadcasting, photography and performing arts assistants and operators' },
  { code: '53120', title: 'Dancers' },
  { code: '53121', title: 'Actors, comedians and circus performers' },
  { code: '53122', title: 'Painters, sculptors and other visual artists' },
  { code: '53123', title: 'Theatre, fashion, exhibit and other creative designers' },
  { code: '53124', title: 'Artisans and craftspersons' },
  { code: '53125', title: 'Patternmakers – textile, leather and fur products' },
  { code: '53200', title: 'Athletes' },
  { code: '53201', title: 'Coaches' },
  { code: '53202', title: 'Sports officials and referees' },
  { code: '54100', title: 'Program leaders and instructors in recreation, sport and fitness' },
  { code: '55109', title: 'Other performers' },
  { code: '60010', title: 'Corporate sales managers' },
  { code: '60020', title: 'Retail and wholesale trade managers' },
  { code: '60030', title: 'Restaurant and food service managers' },
  { code: '60031', title: 'Accommodation service managers' },
  { code: '60040', title: 'Managers in customer and personal services' },
  { code: '62010', title: 'Retail sales supervisors' },
  { code: '62020', title: 'Food service supervisors' },
  { code: '62021', title: 'Executive housekeepers' },
  { code: '62022', title: 'Accommodation, travel, tourism, and related services supervisors' },
  { code: '62023', title: 'Customer and information services supervisors' },
  { code: '62024', title: 'Cleaning supervisors' },
  { code: '62029', title: 'Other services supervisors' },
  { code: '62100', title: 'Technical sales specialists – wholesale trade' },
  { code: '62101', title: 'Retail and wholesale buyers' },
  { code: '62200', title: 'Chefs' },
  { code: '62201', title: 'Funeral directors and embalmers' },
  { code: '62202', title: 'Jewellers, jewellery and watch repairers, and related occupations' },
  { code: '63100', title: 'Insurance agents and brokers' },
  { code: '63101', title: 'Real estate agents and salespersons' },
  { code: '63102', title: 'Financial sales representatives' },
  { code: '63200', title: 'Cooks' },
  { code: '63201', title: 'Butchers – retail and wholesale' },
  { code: '63202', title: 'Bakers' },
  { code: '63210', title: 'Hairstylists and barbers' },
  { code: '63211', title: 'Estheticians, electrologists and related occupations' },
  { code: '63220', title: 'Shoe repairers and shoemakers' },
  { code: '63221', title: 'Upholsterers' },
  { code: '64100', title: 'Retail salespersons and visual merchandisers' },
  { code: '64101', title: 'Sales and account representatives – wholesale trade (non-technical)' },
  { code: '64200', title: 'Tailors, dressmakers, furriers, and milliners' },
  { code: '64201', title: 'Image, social, and other personal consultants' },
  { code: '64300', title: 'Maîtres d’hôtel and hosts/hostesses' },
  { code: '64301', title: 'Bartenders' },
  { code: '64310', title: 'Travel counselors' },
  { code: '64311', title: 'Pursers and flight attendants' },
  { code: '64312', title: 'Airline ticket and service agents' },
  { code: '64313', title: 'Ground and water transport ticket agents, cargo service representatives, and related clerks' },
  { code: '64314', title: 'Hotel front desk clerks' },
  { code: '64320', title: 'Tour and travel guides' },
  { code: '64321', title: 'Casino workers' },
  { code: '64322', title: 'Outdoor sport and recreational guides' },
  { code: '64400', title: 'Customer services representatives – financial institutions' },
  { code: '64401', title: 'Postal services representatives' },
  { code: '64409', title: 'Other customer and information services representatives' },
  { code: '64410', title: 'Security guards and related security service occupations' },
  { code: '65100', title: 'Cashiers' },
  { code: '65101', title: 'Service station attendants' },
  { code: '65102', title: 'Store shelf stockers, clerks, and order fillers' },
  { code: '65109', title: 'Other sales-related occupations' },
  { code: '65200', title: 'Food and beverage servers' },
  { code: '65201', title: 'Food counter attendants, kitchen helpers, and related support occupations' },
  { code: '65202', title: 'Meat cutters and fishmongers – retail and wholesale' },
  { code: '65210', title: 'Support occupations in accommodation, travel, and facilities set-up services' },
  { code: '65211', title: 'Operators and attendants in amusement, recreation, and sport' },
  { code: '65220', title: 'Pet groomers and animal care workers' },
  { code: '65229', title: 'Other support occupations in personal services' },
  { code: '65310', title: 'Light duty cleaners' },
  { code: '65311', title: 'Specialized cleaners' },
  { code: '65312', title: 'Janitors, caretakers, and heavy-duty cleaners' },
  { code: '65320', title: 'Dry cleaning, laundry, and related occupations' },
  { code: '65329', title: 'Other service support occupations' },
  { code: '70010', title: 'Construction managers' },
  { code: '70011', title: 'Home building and renovation managers' },
  { code: '70012', title: 'Facility operation and maintenance managers' },
  { code: '70020', title: 'Managers in transportation' },
  { code: '70021', title: 'Postal and courier services managers' },
  { code: '72010', title: 'Contractors and supervisors, machining, metal forming, shaping and erecting trades, and related occupations' },
  { code: '72011', title: 'Contractors and supervisors, electrical trades, and telecommunications occupations' },
  { code: '72012', title: 'Contractors and supervisors, pipefitting trades' },
  { code: '72013', title: 'Contractors and supervisors, carpentry trades' },
  { code: '72014', title: 'Contractors and supervisors, other construction trades, installers, repairers, and servicers' },
  { code: '72020', title: 'Contractors and supervisors, mechanic trades' },
  { code: '72021', title: 'Contractors and supervisors, heavy equipment operator crews' },
  { code: '72022', title: 'Supervisors, printing, and related occupations' },
  { code: '72023', title: 'Supervisors, railway transport operations' },
  { code: '72024', title: 'Supervisors, motor transport, and other ground transit operators' },
  { code: '72025', title: 'Supervisors, mail and message distribution occupations' },
  { code: '72100', title: 'Machinists and machining and tooling inspectors' },
  { code: '72101', title: 'Tool and die makers' },
  { code: '72102', title: 'Sheet metal workers' },
  { code: '72103', title: 'Boilermakers' },
  { code: '72104', title: 'Structural metal and plate work fabricators and fitters' },
  { code: '72105', title: 'Ironworkers' },
  { code: '72106', title: 'Welders and related machine operators' },
  { code: '72200', title: 'Electricians (except industrial and power systems)' },
  { code: '72201', title: 'Industrial electricians' },
  { code: '72202', title: 'Power system electricians' },
  { code: '72203', title: 'Electrical power line and cable workers' },
  { code: '72204', title: 'Telecommunications line and cable installers and repairers' },
  { code: '72205', title: 'Telecommunications equipment installation and cable television service technicians' },
  { code: '72300', title: 'Plumbers' },
  { code: '72301', title: 'Steamfitters, pipefitters, and sprinkler system installers' },
  { code: '72302', title: 'Gas fitters' },
  { code: '72310', title: 'Carpenters' },
  { code: '72311', title: 'Cabinetmakers' },
  { code: '72320', title: 'Bricklayers' },
  { code: '72321', title: 'Insulators' },
  { code: '72400', title: 'Construction millwrights and industrial mechanics' },
  { code: '72401', title: 'Heavy-duty equipment mechanics' },
  { code: '72402', title: 'Heating, refrigeration, and air conditioning mechanics' },
  { code: '72403', title: 'Railway carmen/women' },
  { code: '72404', title: 'Aircraft mechanics and aircraft inspectors' },
  { code: '72405', title: 'Machine fitters' },
  { code: '72406', title: 'Elevator constructors and mechanics' },
  { code: '72410', title: 'Automotive service technicians, truck and bus mechanics, and mechanical repairers' },
  { code: '72411', title: 'Auto body collision, refinishing, and glass technicians and damage repair estimators' },
  { code: '72420', title: 'Oil and solid fuel heating mechanics' },
  { code: '72421', title: 'Appliance servicers and repairers' },
  { code: '72422', title: 'Electrical Mechanics' },
  { code: '72423', title: 'Motorcycle, all-terrain vehicle, and other related mechanics' },
  { code: '72429', title: 'Other small engine and small equipment repairers' },
  { code: '72500', title: 'Crane operators' },
  { code: '72501', title: 'Water well drillers' },
  { code: '72600', title: 'Air pilots, flight engineers, and flying instructors' },
  { code: '72601', title: 'Air traffic controllers and related occupations' },
  { code: '72602', title: 'Deck officers, water transport' },
  { code: '72603', title: 'Engineer officers, water transport' },
  { code: '72604', title: 'Railway traffic controllers and marine traffic regulators' },
  { code: '72999', title: 'Other technical trades and related occupations' },
  { code: '73100', title: 'Concrete finishers' },
  { code: '73101', title: 'Tilesetters' },
  { code: '73102', title: 'Plasterers, drywall installers and finishers and lathers' },
  { code: '73110', title: 'Roofers and shinglers' },
  { code: '73111', title: 'Glaziers' },
  { code: '73112', title: 'Painters and decorators (except interior decorators)' },
  { code: '73113', title: 'Floor covering installers' },
  { code: '73200', title: 'Residential and commercial installers and servicers' },
  { code: '73201', title: 'General building maintenance workers and building superintendents' },
  { code: '73202', title: 'Pest controllers and fumigators' },
  { code: '73209', title: 'Other repairers and servicers' },
  { code: '73300', title: 'Transport truck drivers' },
  { code: '73301', title: 'Bus drivers, subway operators and other transit operators' },
  { code: '73310', title: 'Railway and yard locomotive engineers' },
  { code: '73311', title: 'Railway conductors and brakemen/women' },
  { code: '73400', title: 'Heavy equipment operators' },
  { code: '73401', title: 'Printing press operators' },
  { code: '73402', title: 'Drillers and blasters – surface mining, quarrying and construction' },
  { code: '74100', title: 'Mail and parcel sorters and related occupations' },
  { code: '74101', title: 'Letter carriers' },
  { code: '74102', title: 'Couriers and messengers' },
  { code: '74200', title: 'Railway yard and track maintenance workers' },
  { code: '74201', title: 'Water transport deck and engine room crew' },
  { code: '74202', title: 'Air transport ramp attendants' },
  { code: '74203', title: 'Automotive and heavy truck and equipment parts installers and servicers' },
  { code: '74204', title: 'Utility maintenance workers' },
  { code: '74205', title: 'Public works maintenance equipment operators and related workers' },
  { code: '75100', title: 'Longshore workers' },
  { code: '75101', title: 'Material handlers' },
  { code: '75110', title: 'Construction trades helpers and labourers' },
  { code: '75119', title: 'Other trades helpers and labourers' },
  { code: '75200', title: 'Taxi and limousine drivers and chauffeurs' },
  { code: '75201', title: 'Delivery service drivers and door-to-door distributors' },
  { code: '75210', title: 'Boat and cable ferry operators and related occupations' },
  { code: '75211', title: 'Railway and motor transport labourers' },
  { code: '75212', title: 'Public works and maintenance labourers' },
  { code: '80010', title: 'Managers in natural resources production and fishing' },
  { code: '80020', title: 'Managers in agriculture' },
  { code: '80021', title: 'Managers in horticulture' },
  { code: '80022', title: 'Managers in aquaculture' },
  { code: '82010', title: 'Supervisors, logging and forestry' },
  { code: '82020', title: 'Supervisors, mining, and quarrying' },
  { code: '82021', title: 'Contractors and supervisors, oil and gas drilling and services' },
  { code: '82030', title: 'Agricultural service contractors and farm supervisors' },
  { code: '82031', title: 'Contractors and supervisors, landscaping, grounds maintenance, and horticulture services' },
  { code: '83100', title: 'Underground production and development miners' },
  { code: '83101', title: 'Oil and gas well drillers, servicers, testers and related workers' },
  { code: '83110', title: 'Logging machinery operators' },
  { code: '83120', title: 'Fishing masters and officers' },
  { code: '83121', title: 'Fishermen/women' },
  { code: '84100', title: 'Underground mine service and support workers' },
  { code: '84101', title: 'Oil and gas well drilling and related workers and services operators' },
  { code: '84110', title: 'Chainsaw and skidder operators' },
  { code: '84111', title: 'Silviculture and forestry workers' },
  { code: '84120', title: 'Specialized livestock workers and farm machinery operators' },
  { code: '84121', title: 'Fishing vessel deckhands' },
  { code: '85100', title: 'Livestock labourers' },
  { code: '85101', title: 'Harvesting labourers' },
  { code: '85102', title: 'Aquaculture and marine harvest labourers' },
  { code: '85103', title: 'Nursery and greenhouse labourers' },
  { code: '85104', title: 'Trappers and hunters' },
  { code: '85110', title: 'Mine labourers' },
  { code: '85111', title: 'Oil and gas drilling, servicing and related labourers' },
  { code: '85120', title: 'Logging and forestry labourers' },
  { code: '85121', title: 'Landscaping and grounds maintenance labourers' },
  { code: '90010', title: 'Manufacturing managers' },
  { code: '90011', title: 'Utilities managers' },
  { code: '92010', title: 'Supervisors, mineral and metal processing' },
  { code: '92011', title: 'Supervisors, petroleum, gas and chemical processing, and utilities' },
  { code: '92012', title: 'Supervisors, food and beverage processing' },
  { code: '92013', title: 'Supervisors, plastic and rubber products manufacturing' },
  { code: '92014', title: 'Supervisors, forest products processing' },
  { code: '92015', title: 'Supervisors, textile, fabric, fur, and leather products processing, and manufacturing' },
  { code: '92020', title: 'Supervisors, motor vehicle assembling' },
  { code: '92021', title: 'Supervisors, electronics and electrical products manufacturing' },
  { code: '92022', title: 'Supervisors, furniture, and fixtures manufacturing' },
  { code: '92023', title: 'Supervisors, other mechanical and metal products manufacturing' },
  { code: '92024', title: 'Supervisors, other products manufacturing and assembly' },
  { code: '92100', title: 'Power engineers and power systems operators' },
  { code: '92101', title: 'Water and waste treatment plant operators' },
  { code: '93100', title: 'Central control and process operators, mineral and metal processing' },
  { code: '93101', title: 'Central control and process operators, petroleum, gas and chemical processing' },
  { code: '93102', title: 'Pulping, papermaking and coating control operators' },
  { code: '93200', title: 'Aircraft assemblers and aircraft assembly inspectors' },
  { code: '94100', title: 'Machine operators, mineral and metal processing' },
  { code: '94101', title: 'Foundry workers' },
  { code: '94102', title: 'Glass forming and finishing machine operators and glass cutters' },
  { code: '94103', title: 'Concrete, clay, and stone forming operators' },
  { code: '94104', title: 'Inspectors and testers, mineral and metal processing' },
  { code: '94105', title: 'Metalworking and forging machine operators' },
  { code: '94106', title: 'Machining tool operators' },
  { code: '94107', title: 'Machine operators of other metal products' },
  { code: '94110', title: 'Chemical plant machine operators' },
  { code: '94111', title: 'Plastics processing machine operators' },
  { code: '94112', title: 'Rubber processing machine operators and related workers' },
  { code: '94120', title: 'Sawmill machine operators' },
  { code: '94121', title: 'Pulp mill, papermaking, and finishing machine operators' },
  { code: '94122', title: 'Paper-converting machine operators' },
  { code: '94123', title: 'Lumber graders and other wood processing inspectors and graders' },
  { code: '94124', title: 'Woodworking machine operators' },
  { code: '94129', title: 'Other wood-processing machine operators' },
  { code: '94130', title: 'Textile fiber and yarn, hide and pelt processing machine operators and workers' },
  { code: '94131', title: 'Weavers, knitters, and other fabric-making occupations' },
  { code: '94132', title: 'Industrial sewing machine operators' },
  { code: '94133', title: 'Inspectors and graders, textile, fabric, fur, and leather products manufacturing' },
  { code: '94140', title: 'Process control and machine operators, food and beverage processing' },
  { code: '94141', title: 'Industrial butchers and meat cutters, poultry preparers, and related workers' },
  { code: '94142', title: 'Fish and seafood plant workers' },
  { code: '94143', title: 'Testers and graders, food and beverage processing' },
  { code: '94150', title: 'Plateless printing equipment operators' },
  { code: '94151', title: 'Camera, plate making and other prepress occupations' },
  { code: '94152', title: 'Binding and finishing machine operators' },
  { code: '94153', title: 'Photographic and film processors' },
  { code: '94200', title: 'Motor vehicle assemblers, inspectors, and testers' },
  { code: '94201', title: 'Electronics assemblers, fabricators, inspectors, and testers' },
  { code: '94202', title: 'Assemblers and inspectors, electrical appliance, apparatus, and equipment manufacturing' },
  { code: '94203', title: 'Assemblers, fabricators and inspectors, industrial electric motors and transformers' },
  { code: '94204', title: 'Mechanical assemblers and inspectors' },
  { code: '94205', title: 'Machine operators and inspectors, electrical apparatus manufacturing' },
  { code: '94210', title: 'Furniture and fixture assemblers, finishers, refinishers, and inspectors' },
  { code: '94211', title: 'Assemblers and inspectors of other wood products' },
  { code: '94212', title: 'Plastic products assemblers, finishers, and inspectors' },
  { code: '94213', title: 'Industrial painters, coaters, and metal-finishing process operators' },
  { code: '94219', title: 'Other products assemblers, finishers, and inspectors' },
  { code: '95100', title: 'Labourers in mineral and metal processing' },
  { code: '95101', title: 'Labourers in metal fabrication' },
  { code: '95102', title: 'Labourers in chemical products processing and utilities' },
  { code: '95103', title: 'Labourers in wood, pulp, and paper processing' },
  { code: '95104', title: 'Labourers in rubber and plastic products manufacturing' },
  { code: '95105', title: 'Labourers in textile processing and cutting' },
  { code: '95106', title: 'Labourers in food and beverage processing' },
  { code: '95107', title: 'Labourers in fish and seafood processing' },
  { code: '95109', title: 'Other labourers in processing, manufacturing, and utilities' },
] as const

const BY_CODE = new Map(NOC_UNIT_GROUPS.map((g) => [g.code, g]))

/**
 * Every valid code, for use as a JSON-schema `enum`. Constraining the model's
 * output to this set at the schema level means an invented code cannot be
 * produced in the first place; `isValidNocCode` is the second line of defence.
 */
export const NOC_CODES: readonly string[] = NOC_UNIT_GROUPS.map((g) => g.code)

/**
 * The full `code title` list as one string, for dropping into a prompt so the
 * model can actually choose between codes. Built once at module load — it is
 * roughly 26 KB, so read it, never rebuild it per request.
 */
export const NOC_REFERENCE_LIST: string = NOC_UNIT_GROUPS.map(
  (g) => `${g.code} ${g.title}`
).join('\n')

/**
 * Whether a string is a real NOC 2021 unit group code.
 * Every LLM-produced code must pass through this before it is stored or shown —
 * a plausible-looking but non-existent NOC code is worse than no code at all,
 * because employers and immigration programs check it.
 */
export function isValidNocCode(code: unknown): code is string {
  return typeof code === 'string' && BY_CODE.has(code)
}

export function nocByCode(code: string): NocUnitGroup | undefined {
  return BY_CODE.get(code)
}

export function nocTitle(code: string): string | undefined {
  return BY_CODE.get(code)?.title
}

/** TEER category, read off the second digit. Undefined for unknown codes. */
export function teerOf(code: string): TeerCategory | undefined {
  if (!isValidNocCode(code)) return undefined
  return Number(code[1]) as TeerCategory
}

export function teerLabel(code: string): string | undefined {
  const teer = teerOf(code)
  return teer === undefined ? undefined : TEER_LABELS[teer]
}

export function broadCategoryOf(code: string): string | undefined {
  if (!isValidNocCode(code)) return undefined
  return BROAD_CATEGORIES[code[0]]
}

/**
 * TEER 0-3 is the usual bar for Express Entry's skilled-worker streams. This is
 * a display hint only — actual program eligibility depends on far more than the
 * code, so never present it to a user as an eligibility determination.
 */
export function isSkilledTeer(code: string): boolean {
  const teer = teerOf(code)
  return teer !== undefined && teer <= 3
}
